# نمونه فایل پیکربندی برای FlyzexBot
telegram:
  bot_token_env: BOT_TOKEN  # نام متغیر محیطی که توکن در آن قرار می‌گیرد
  owner_id: 123456789  # شناسه مدیر اصلی بات
  application_review_chat: null  # در صورت نیاز می‌توانید شناسه چت خاصی برای اعلان درخواست‌ها تعیین کنید
xp:
  message_character_reward: 1  # XP به ازای هر کاراکتر پیام؛ مقدار 0 سیستم XP را غیرفعال می‌کند
  message_reward_limit: 20      # بیشترین XP قابل دریافت از هر پیام
  message_reward_cooldown: 20   # فاصله زمانی (ثانیه) برای دریافت دوباره XP پس از هر پیام
  leaderboard_size: 10
  milestone_interval: 5
cups:
  leaderboard_size: 5
storage:
  path: data/storage.json
  backup_path: data/storage.sqlite
logging:
  level: INFO
  file: logs/bot.log
webapp:
  host: 0.0.0.0
  port: 8080
  url: https://example.com/flyzex
system:
  timezone: UTC+03:30
